#!/usr/bin/env python

import argparse
import subprocess
import sys


if __name__ == "__main__":
    description = """Builds CKAN deb packages.
This script essentially sets up the necessary vars and calls `docker buildx build`."""
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument(
        "ref",
        help="The CKAN branch or tag to build (e.g. master, dev-v2.11, ckan-2.10.6...)",
    )
    parser.add_argument(
        "target", help="The Ubuntu distribution to target (e.g. focal, jammy, noble...)"
    )
    parser.add_argument(
        "-i",
        "--iteration",
        default="1",
        help="The iteration number to add to the package name.",
    )

    args = parser.parse_args()

    ref = args.ref
    target = args.target
    iteration = args.iteration

    supported_targets = {}
    with open("UBUNTU_VERSIONS.txt") as f:
        for line in f.readlines():
            [version, name] = line.split()
            supported_targets[name] = version

    if target not in supported_targets.keys():
        print(f"Wrong target: {target}")
        sys.exit(1)

    command = [
        "docker",
        "buildx",
        "build",
        "--output",
        "type=local,dest=.",
        "--build-arg",
        f"CKAN_REF={ref}",
        "--build-arg",
        f"ITERATION={iteration}",
        "--build-arg",
        f"UBUNTU_VERSION={supported_targets[target]}",
        ".",
    ]

    subprocess.call(command)
