---
    - name: copy source who.ini to configuration folder for CKAN 2.9
      action: command cp /usr/lib/ckan/default/src/ckan/who.ini /etc/ckan/default/who.ini

    - name: copy executables for CKAN 2.9
      action: copy src=common/{{ item }} dest=/{{ item }} mode=744
      with_items:
        - usr/bin/ckan
